from app.prompts.system_prompts import (
    RAG_SYSTEM_PROMPT,
    SUMMARY_PROMPT,
    QUIZ_PROMPT,
    FLASHCARDS_PROMPT,
    EXAM_QUESTIONS_PROMPT,
    SUGGESTED_QUESTIONS_PROMPT,
)

__all__ = [
    "RAG_SYSTEM_PROMPT",
    "SUMMARY_PROMPT",
    "QUIZ_PROMPT",
    "FLASHCARDS_PROMPT",
    "EXAM_QUESTIONS_PROMPT",
    "SUGGESTED_QUESTIONS_PROMPT",
]
