// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzsjjjbetjcybovnyaaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16c2pqamJldGpjeWJvdm55YWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTE3NTksImV4cCI6MjA2ODc2Nzc1OX0.S20798FZFXUidjIZWUYRcPoqpt8emdE4QRQkJmo427o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});